name: Build Check

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - uses: spacey-sooty/Actions-For-GradleRIO@master
      with:
        os: ubuntu
    - name: Toolchain
      run: ./gradlew installRoboRIOToolChain
    - name: Checkout
      run: git clone https://github.com/curtinFRC/Wombat.git wombat
    - name: Build
      run: ./gradlew build

